SELECT DISTINCT ?0 WHERE {
 ?0 a <http://benchmark/OWL2Bench#UGCourse> .
 ?0 <http://benchmark/OWL2Bench#isTaughtBy> ?1 .
 ?1 a <http://benchmark/OWL2Bench#Man> .
 ?1 <http://benchmark/OWL2Bench#likes> ?2 .
 ?2 a <http://benchmark/OWL2Bench#Music> .
}